### ISSUE TITLE
The impact of noise on positioning

### ISSUE THREAD

**Issue by eithwa** [alifahrri/robosoccer-mcl#1]
I apply your program on our robot
but I noticed that the noise has a very serious impact on positioning when it is at the border or in the corner.（On the right side of the picture is the  input. On the left is the localization.）
How can I improve this problem? Thank you.
![Alt text](https://i.imgur.com/VXQIGOs.png)
![Alt text](https://i.imgur.com/Ijy5hH9.png)

**Comment by alifahrri** [comment]
Hi, I noticed that on your first picture you used FIRA map, right? If you have different map, you have to recalculate the [errortable](https://github.com/alifahrri/robosoccer-mcl/tree/master/res) which is the distance to nearest field line.
On your second picture, I think it is weighting problem, not enough weighting difference between aligned and unaligned point so that the misaligned particle not penalized more. Maybe you can try different weighting function (I only implement quadratic function, you may also try qubic, exponential, etc), [check this line](https://github.com/alifahrri/robosoccer-mcl/blob/f57a7b001d91c42d95bc158a6de73a57664daf39/src/mcl.cpp#L123).

**Comment by eithwa** [comment]
Hello, I have modified the errorable information in the first picture, but I can't solve the problem of noise.
I use the green field to filter noise and it works well.
I will do research on the weight part.
Thank you

**Comment by alifahrri** [comment]
Oh yeah I see, [current implementation](https://github.com/alifahrri/robosoccer-mcl/blob/f57a7b001d91c42d95bc158a6de73a57664daf39/src/mcl.cpp#L366) returns a constant value if the points lie outside the field that might have caused the weight calculation unbalanced. Filtering does the trick, i'm closing this issue.
